# site settings
title: Subspace Signal
subtitle:
email: sayhi@subspacesignal.com
description: Digital product development with our lean team of engineers.
baseurl: '' # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address:
city: New York
state: NY
zip_code:
country:
phone:

meta:
  title: Pioneering remote software engineering
  description: Digital product development with our lean team of engineers.

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

clients:
  title: We've worked with
  logos:
    - name: Amnesty International
      image: amnesty.png
      url: https://amnesty.org
    - name: International Budget Partnership
      image: international-budget-partnership.png
      url: https://www.internationalbudget.org/
    - name: European Space Agency
      image: european-space-agency.png
      url: https://www.esa.int/
    - name: European Space Agency Phi Lab
      image: esa-philab.png
      url: https://blogs.esa.int/philab/
    - name: Deutsche Bank
      image: deutsche-bank.png
      url: https://www.db.com/usa/
    - name: Societe Generale
      image: societe-generale.png
      url: https://www.societegenerale.com/en/home
    - name: New York Magazine
      image: new-york-magazine.png
      url: https://nymag.com/
    - name: Government of Canada
      image: government-of-canada.png
      url: https://www.canada.ca/en.html
    - name: US State Department
      image: us-state-department.png
      url: https://www.state.gov/
    - name: German Research Center for Artificial Intelligence
      image: german-research-center-for-artificial-intelligence.png
      url: https://www.dfki.de/en/web/
    - name: University of Turin
      image: university-of-turin.png
      url: https://en.unito.it/

# social settings
500px_url:
facebook_url: https://www.facebook.com/georgeslabreche
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/georgeslabreche/
pinterest_url:
slack_url:
twitter_url: https://www.twitter.com/georgeslabreche

# build settings
markdown: kramdown

sass:
  style: compressed
